// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using Shoop.Data;
using Shoop.Data.Query;

namespace ROMtests
{
    /// <summary>
    ///This is a test class for rom.Data.ObjectQuery and is intended
    ///to contain all rom.Data.ObjectQuery Unit Tests
    ///</summary>
    [TestClass()]
    public class URIQueryTest
    {


        private TestContext testContextInstance;

        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }
        #region Additional test Attributes
        // 
        //You can use the following additional Attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        //
        //[ClassInitialize()]
        //public static void MyClassInitialize(TestContext testContext)
        //{
        //}
        //
        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //
        #endregion

        [TestMethod()]
        public void ParseURIOnlyTest()
        {
            string uri = "myTestURI";
            ObjectQuery query = ObjectQuery.parse(uri);

            Assert.AreEqual(uri, query.UriName, "URI and queryURI are not equal");
            Assert.IsTrue(query.TypeName == null || query.TypeName == string.Empty, "TypeName parameter is not empty");
        }

        /// <summary>
        ///A test for parse (string)
        ///</summary>
        [TestMethod()]
        public void SimpleParseTest()
        {
            string typeName = "players";
            string uriName = "Ted";
            string uriQueryString = typeName + ":" + uriName;

            ObjectQuery actual;

            actual = ObjectQuery.parse(uriQueryString);

            ObjectQuery expected = new ObjectQuery(typeName, uriName);

            Assert.AreEqual(expected, actual, "rom.Data.ObjectQuery.parse did not return the expected value.");
        }

        [TestMethod()]
        public void ComplexParseTest()
        {
            string typeName = "players";
            string uriName = "Ted";
            string typeName2 = "objects";
            string uriName2 = "sword";
            string uriQueryString = typeName + ":" + uriName + "/" + typeName2 + ":" + uriName2;

            ObjectQuery actual;

            actual = ObjectQuery.parse(uriQueryString);

            ObjectQuery expected = new ObjectQuery(typeName, uriName, new ObjectQuery(typeName2, uriName2));

            Assert.AreEqual(expected, actual, "rom.Data.ObjectQuery.parse did not return the expected value.");
        }

        /// <summary>
        ///A test for ObjectQuery (string)
        ///</summary>
        [TestMethod()]
        public void ConstructorURITest()
        {
            string uri = "myURIName";

            ObjectQuery target = new ObjectQuery(uri);

            Assert.AreEqual(uri, target.UriName, "URI's do not match on ObjectQuery ctor");
            Assert.IsNull(target.Subquery, "SubQuery should be null on ObjectQuery ctor");
            Assert.IsNull(target.TypeName, "TypeName should be null on ObjectQuery ctor");
        }

        /// <summary>
        ///A test for ObjectQuery (string, string)
        ///</summary>
        [TestMethod()]
        public void ConstructorTypeURITest()
        {
            string type = "objType";
            string uri = "myURIName";

            ObjectQuery target = new ObjectQuery(type, uri);

            Assert.AreEqual(type, target.TypeName, "TypeName's do not match on ObjectQuery ctor");
            Assert.AreEqual(uri, target.UriName, "URI's do not match on ObjectQuery ctor");
            Assert.IsNull(target.Subquery, "SubQuery should be null on ObjectQuery ctor");
        }

        /// <summary>
        ///A test for ObjectQuery (string, string, ObjectQuery)
        ///</summary>
        [TestMethod()]
        public void ConstructorAllTest()
        {
            string type = "objType";
            string uri = "myURIName";
            ObjectQuery subQuery = new ObjectQuery("type2", "uri2");

            ObjectQuery target = new ObjectQuery(type, uri, subQuery);

            Assert.AreEqual(type, target.TypeName, "TypeName's do not match on ObjectQuery ctor");
            Assert.AreEqual(uri, target.UriName, "URI's do not match on ObjectQuery ctor");
            Assert.AreSame(subQuery, target.Subquery, "SubQuery does not match on ObjectQuery ctor");
        }


        /// <summary>
        ///A test for Equals (object)
        ///</summary>
        [TestMethod()]
        public void EqualsTest()
        {
            string type = "players";
            string uri = "Ted";

            string type2 = "objects";
            string uri2 = "sword";

            ObjectQuery expected = new ObjectQuery(type, uri, new ObjectQuery(type2, uri2));

            ObjectQuery actual = new ObjectQuery(type, uri, new ObjectQuery(type2, uri2));

            Assert.AreEqual<ObjectQuery>(expected, actual, "rom.Data.ObjectQuery.Equals did not return the expected value.");
        }
    }


}
