// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using Shoop.Data.Query;
using Shoop.Data;

namespace ROMtests
{
    /// <summary>
    ///This is a test class for Shoop.Data.Query.QueryableCollectionAdapter&lt;T&gt; and is intended
    ///to contain all Shoop.Data.Query.QueryableCollectionAdapter&lt;T&gt; Unit Tests
    ///</summary>
    [TestClass()]
    public class QueryableCollectionAdapterTest
    {


        private TestContext testContextInstance;

        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }
        #region Additional test attributes
        // 
        //You can use the following additional attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        //
        //[ClassInitialize()]
        //public static void MyClassInitialize(TestContext testContext)
        //{
        //}
        //
        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //
        #endregion


        /// <summary>
        ///A test for QueryableCollectionAdapter (ICollection&lt;T&gt;, string)
        ///</summary>
        [TestMethod()]
        public void ListTest()
        {
            Player o1 = new Player();
            Player o2 = new Player();
            Player o3 = new Player();

            o1.URI = "ant";
            o2.URI = "cat";
            o3.URI = "carp";

            List<Player> list = new List<Player>();
            list.Add(o1);
            list.Add(o2);
            list.Add(o3);

            IQueryable wrapper = new QueryableCollectionAdapter<Player>(list, "animates");

            IQueryable actual = wrapper.Find("cat");
            Assert.AreSame(o2, actual);
        }

    }


}
