//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1378
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mirage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mirage.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m inside ${otherTemplate}..
        /// </summary>
        internal static string IncludedTemplate {
            get {
                return ResourceManager.GetString("IncludedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${player} has arrived..
        /// </summary>
        internal static string Movement_Arrival {
            get {
                return ResourceManager.GetString("Movement.Arrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command can not be executed by a ${ActorType}..
        /// </summary>
        internal static string msg__common_error_InvalidActor {
            get {
                return ResourceManager.GetString("msg:/common/error/InvalidActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huh?.
        /// </summary>
        internal static string msg__common_error_InvalidCommand {
            get {
                return ResourceManager.GetString("msg:/common/error/InvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${target} is not here..
        /// </summary>
        internal static string msg__common_error_NotHere {
            get {
                return ResourceManager.GetString("msg:/common/error/NotHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${player} is not playing right now..
        /// </summary>
        internal static string msg__common_error_PlayerNotPlaying {
            get {
                return ResourceManager.GetString("msg:/common/error/PlayerNotPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${player} says &apos;${message}&apos;..
        /// </summary>
        internal static string msg__communication_say_others {
            get {
                return ResourceManager.GetString("msg:/communication/say.others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You said &apos;${message}&apos;..
        /// </summary>
        internal static string msg__communication_say_self {
            get {
                return ResourceManager.GetString("msg:/communication/say.self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${player} tells you &apos;${message}&apos;..
        /// </summary>
        internal static string msg__communication_tell_others {
            get {
                return ResourceManager.GetString("msg:/communication/tell.others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You tell ${target} &apos;${message}&apos;..
        /// </summary>
        internal static string msg__communication_tell_self {
            get {
                return ResourceManager.GetString("msg:/communication/tell.self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace test message.
        /// </summary>
        internal static string msg__namespace_test {
            get {
                return ResourceManager.GetString("msg:/namespace/test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That player is already playing..
        /// </summary>
        internal static string msg__negotiation_authentication_player_already_playing {
            get {
                return ResourceManager.GetString("msg:/negotiation/authentication/player.already.playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        /// $$$$$$$
        ///$$$$$$$$$$
        ///$$$            III
        /// $$$           III
        ///  $$$          III
        ///   $$$         III
        ///    $$$        III IIII
        ///     $$$       IIIIII III     OOOOOOOOO      OOOOOOOOO      OOOOOOOOO
        ///      $$$      IIIII   III   OOOOOOOOOOO    OOOOOOOOOOO    OOOOOOOOOOO
        ///       $$$     III      III  OOO     OOO    OOO     OOO    OOO     OOO
        ///       $$$$    III      III  OOO     OOO    OOO     OOO    OOO     OOO
        ///$$$    $$$$    III      III  OOO     OOO    OOO     OOO    OOO     OOO
        ///$$$  $$$$      III     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string msg__negotiation_splash {
            get {
                return ResourceManager.GetString("msg:/negotiation/splash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Welcome to MirageMUD 0.1.  Still in development..
        /// </summary>
        internal static string msg__negotiation_welcome {
            get {
                return ResourceManager.GetString("msg:/negotiation/welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A system error has occurred executing your command..
        /// </summary>
        internal static string msg__system_error_SystemError {
            get {
                return ResourceManager.GetString("msg:/system/error/SystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goodbye!.
        /// </summary>
        internal static string msg__system_goodbye {
            get {
                return ResourceManager.GetString("msg:/system/goodbye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This template contains ( @{IncludedTemplate} ) custom = ${custom}.
        /// </summary>
        internal static string TestTemplateInclude {
            get {
                return ResourceManager.GetString("TestTemplateInclude", resourceCulture);
            }
        }
    }
}
