// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using Shoop.Data;
using System.Collections.Specialized;
using System.Configuration;
using System.IO;
namespace ROMtests
{
    /// <summary>
    ///This is a test class for rom.Data.Player and is intended
    ///to contain all rom.Data.Player Unit Tests
    ///</summary>
    [TestClass()]
    public class PlayerTest
    {


        private TestContext testContextInstance;

        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }
        #region Additional test Attributes
        // 
        //You can use the following additional Attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        //
        [ClassInitialize()]
        public static void MyClassInitialize(TestContext testContext)
        {
            NameValueCollection settings = ConfigurationManager.AppSettings;
            string playerDir = settings["player.dir"];
            // create the player directory
            Directory.CreateDirectory(playerDir);

        }
        //
        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //
        #endregion


        /// <summary>
        ///A test for comparePassword (string)
        ///</summary>
        [TestMethod()]
        public void comparePasswordTest()
        {
            Player target = new Player();
            target.setPassword("mypassword");
            string otherPassword = "mypassword";

            bool expected = true;
            bool actual;

            actual = target.comparePassword(otherPassword);

            Assert.AreEqual(expected, actual, "rom.Data.Player.comparePassword did not return the expected value.");

            target.setPassword("someotherpassword");
            expected = false;
            actual = target.comparePassword(otherPassword);

            Assert.AreEqual(expected, actual, "rom.Data.Player.comparePassword did not return the expected value.");
        }

        /// <summary>
        ///A test for password
        ///</summary>
        [TestMethod()]
        public void passwordTest()
        {
            Player target = new Player();

            string val = "mypassword"; // TODO: Assign to an appropriate value for the property

            target.setPassword(val);


            Assert.AreNotEqual(val, target.password, "rom.Data.Player.password was not encrypted.");
        }

        [TestMethod()]
        public void loadSaveTest()
        {
            Player target = new Player();
            target.URI = "targetName";
            target.title = "targetName";
            target.Description = "target Description line 1\r\ntargeDescriptionon line 2";
            target.setPassword("targetPassword");
            target.level = 23;
            target.sex = SexType.Female;

            Player.save(target);
            Player loaded = Player.load(target.URI);

            Assert.AreEqual(target.title, loaded.title, "rom.Data.Player.title field not equal to loaded value");
        }
    }


}
