{
	"Namespace" : "system",
	"Messages" : {
		"EchoOn" :  new StringMessage ("UIControl",   "EchoOn",  "\u001b[0m" ),
		"EchoOff" : new StringMessage ("UIControl",   "EchoOff", "\u001b[0;30;40m" ),
		"Newline" : new StringMessage ("UIControl",   "Newline", "\r\n" ),
		"goodbye" :	new StringMessage ("Information", "goodbye", "Goodbye!\r\n" ),
		"ConfirmationPrompt" : new StringMessage ("Prompt", "ConfirmationPrompt", "Are you sure? (y\\n) " ),
		"ConfirmationCancel" : new StringMessage ("Information", "ConfirmationCancel", "Command cancelled." )
		
	}
}