//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shoop {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shoop.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${player} says &apos;${message}&apos;..
        /// </summary>
        internal static string Comm_Say_Others {
            get {
                return ResourceManager.GetString("Comm.Say.Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You said &apos;${message}&apos;..
        /// </summary>
        internal static string Comm_Say_Self {
            get {
                return ResourceManager.GetString("Comm.Say.Self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${player} tells you &apos;${message}&apos;..
        /// </summary>
        internal static string Comm_Tell_Others {
            get {
                return ResourceManager.GetString("Comm.Tell.Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You tell &apos;${message}&apos;..
        /// </summary>
        internal static string Comm_Tell_Self {
            get {
                return ResourceManager.GetString("Comm.Tell.Self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huh?.
        /// </summary>
        internal static string Error_InvalidCommand {
            get {
                return ResourceManager.GetString("Error.InvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${player} is not playing right now..
        /// </summary>
        internal static string Error_PlayerNotPlaying {
            get {
                return ResourceManager.GetString("Error.PlayerNotPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m inside ${otherTemplate}..
        /// </summary>
        internal static string IncludedTemplate {
            get {
                return ResourceManager.GetString("IncludedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goodbye!.
        /// </summary>
        internal static string Info_Goodbye {
            get {
                return ResourceManager.GetString("Info.Goodbye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${player} has arrived..
        /// </summary>
        internal static string Movement_Arrival {
            get {
                return ResourceManager.GetString("Movement.Arrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This template contains ( @{IncludedTemplate} ) custom = ${custom}.
        /// </summary>
        internal static string TestTemplateInclude {
            get {
                return ResourceManager.GetString("TestTemplateInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        /// $$$$$$$
        ///$$$$$$$$$$
        ///$$$            III
        /// $$$           III
        ///  $$$          III
        ///   $$$         III
        ///    $$$        III IIII
        ///     $$$       IIIIII III     OOOOOOOOO      OOOOOOOOO      OOOOOOOOO
        ///      $$$      IIIII   III   OOOOOOOOOOO    OOOOOOOOOOO    OOOOOOOOOOO
        ///       $$$     III      III  OOO     OOO    OOO     OOO    OOO     OOO
        ///       $$$$    III      III  OOO     OOO    OOO     OOO    OOO     OOO
        ///$$$    $$$$    III      III  OOO     OOO    OOO     OOO    OOO     OOO
        ///$$$  $$$$      III     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
